### ISSUE TITLE
Multiple validations per input

### ISSUE THREAD

**Issue by dolcy** [Adipa-G/ngFormValidator#1]
Great stuff, but I'm not sure how to chain multiple validations per input e.g. name is required with minimum of 2 characters. Perhaps this is missing in docs. Cheers.

**Comment by dolcy** [comment]
Nice effort, but will stick with Formly. Thanks.

**Comment by Adipa-G** [comment]
Multiple validations can be compared simply using a comma, such as validator="regex['\S+@\S+\.\S+'],string[5,20]"

Thanks for pointing out the missing documentation.
